spring:
  profiles :
    active : local 
  application:
    name: hoeuni

mybatis:
  mapper-locations : "classpath*:mapper/oracle/**/*.xml"
  config-location : "classpath:mybatis-configuration.xml" 
    
server:
  port: 8080
  
logging:
  level:
    com.skcc.hoeuni: DEBUG
    org.springframework.boot: INFO
    org.springframework.security: INFO
    ROOT: INFO
    
---
spring:
  profiles : local
  datasource:
    url: jdbc:oracle:thin:@203.235.211.113:1521/ARCH
    username: stem
    password: stem123
    driver-class-name: oracle.jdbc.OracleDriver

